const $=s=>document.querySelector(s), NS="http://www.w3.org/2000/svg";
let summary=null, manifest=null;
const svgEl=(tag,attrs={})=>{const e=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e};
const human=n=>new Intl.NumberFormat(undefined,{notation:"compact",maximumFractionDigits:1}).format(n);
const bytes=n=>{for(const u of["B","KiB","MiB","GiB","TiB"]){if(n<1024||u==="TiB")return `${n.toFixed(n<10&&u!=="B"?1:0)} ${u}`;n/=1024}};
const duration=s=>{if(s<3600)return `${Math.max(1,Math.round(s/60))}m`;if(s<86400)return `${Math.round(s/3600)}h`;return `${Math.round(s/86400)}d`};
function baseSvg(target,max,{log=false,format=human}={}){target.textContent="";if(!max){target.className="chart empty";target.textContent="No data in this range";return null}target.className="chart";const s=svgEl("svg",{viewBox:"0 0 1000 300","preserveAspectRatio":"none"});for(let i=0;i<5;i++){const y=20+i*55,fraction=(4-i)/4,value=log?Math.expm1(Math.log1p(max)*fraction):max*fraction;s.append(svgEl("line",{x1:55,y1:y,x2:980,y2:y,class:"grid"}));const t=svgEl("text",{x:48,y:y+4,class:"axis","text-anchor":"end"});t.textContent=format(value);s.append(t)}target.append(s);return s}
function bars(target,rows,series){const max=Math.max(0,...rows.flatMap(r=>series.map(x=>r[x.key]))),s=baseSvg(target,max);if(!s)return;const width=925/Math.max(rows.length,1),bar=Math.min(28,width/(series.length+1));rows.forEach((r,i)=>{series.forEach((x,j)=>{const h=r[x.key]/max*220;s.append(svgEl("rect",{x:55+i*width+width/2+(j-(series.length-1)/2)*bar-bar*.42,y:240-h,width:bar*.84,height:h,class:x.class}));});const t=svgEl("text",{x:55+i*width+width/2,y:260,class:"axis","text-anchor":"middle"});t.textContent=r.domain.length>18?r.domain.slice(0,17)+"…":r.domain;s.append(t)});const legend=document.createElement("div");legend.className="legend";series.forEach(x=>{const item=document.createElement("span"),dot=document.createElement("i");dot.className="dot";dot.style.background=x.color;item.append(dot,x.label);legend.append(item)});target.append(legend)}
function bars(target,rows,series,{format=human}={}){const max=Math.max(0,...rows.flatMap(r=>series.map(x=>r[x.key]))),s=baseSvg(target,max,{log:true,format});if(!s)return;const width=925/Math.max(rows.length,1),bar=Math.min(28,width/(series.length+1)),height=value=>Math.log1p(value)/Math.log1p(max)*220;rows.forEach((r,i)=>{series.forEach((x,j)=>{const h=height(r[x.key]),rect=svgEl("rect",{x:55+i*width+width/2+(j-(series.length-1)/2)*bar-bar*.42,y:240-h,width:bar*.84,height:h,class:x.class}),title=svgEl("title");title.textContent=`${r.domain}: ${format(r[x.key])}`;rect.append(title);s.append(rect)});const t=svgEl("text",{x:55+i*width+width/2,y:260,class:"axis","text-anchor":"middle"});t.textContent=r.domain.split(".")[0];s.append(t)});const legend=document.createElement("div");legend.className="legend";series.forEach(x=>{const item=document.createElement("span"),dot=document.createElement("i");dot.className="dot";dot.style.background=x.color;item.append(dot,x.label);legend.append(item)});target.append(legend)}
function line(target,data){const max=Math.max(0,...data.hits,...data.visitors),s=baseSvg(target,max);if(!s)return;const path=values=>values.map((v,i)=>`${i?"L":"M"}${55+i*925/Math.max(values.length-1,1)},${240-v/max*220}`).join(" ");s.append(svgEl("path",{d:path(data.hits),class:"path-hit"}),svgEl("path",{d:path(data.visitors),class:"path-visitor"}));for(let i=0;i<5;i++){const idx=Math.round(i*(data.labels.length-1)/4),t=svgEl("text",{x:55+i*925/4,y:260,class:"axis","text-anchor":i===0?"start":i===4?"end":"middle"});t.textContent=data.labels[idx]||"";s.append(t)}const legend=document.createElement("div");legend.className="legend";legend.innerHTML='<span><i class="dot" style="background:#6999ff"></i>Hits</span><span><i class="dot" style="background:#4ed7cf"></i>Visitors</span>';target.append(legend)}
function tables(){const metric=$("#metric").value;for(const key of["domains","sections","urls"]){const body=$("#top-"+key);body.textContent="";for(const row of summary.top[key][metric]){const tr=document.createElement("tr");for(const value of[row.label,row.hits,row.visitors]){const td=document.createElement("td");td.textContent=value;td.title=String(value);tr.append(td)}body.append(tr)}}}
async function loadLine(){const host=$("#domain").value,file=manifest.series[$("#range").value][host];line($("#timeline"),await fetch(file).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}))}
async function load(){try{$("#status").textContent="Loading…";const range=$("#range").value;summary=await fetch(manifest.summaries[range]).then(r=>r.json());bars($("#activity"),summary.domains,[{key:"hits",label:"Hits",class:"bar-hit",color:"#6999ff"},{key:"visitors",label:"Visitors",class:"bar-visitor",color:"#4ed7cf"}]);bars($("#bandwidth"),summary.domains.map(x=>({...x,bytes_label:bytes(x.bytes)})),[{key:"bytes",label:"Bytes",class:"bar-bytes",color:"#ffb454"}]);const select=$("#domain"),current=select.value;select.textContent="";for(const [value,label] of [["all","All domains"],...manifest.domains.map(x=>[x.id,x.name])]){const o=document.createElement("option");o.value=value;o.textContent=label;select.append(o)}select.value=[...select.options].some(x=>x.value===current)?current:"all";tables();await loadLine();const covered=Math.max(0,Math.min(summary.window.end,summary.window.data_end)-Math.max(summary.window.start,summary.window.data_start));const selected=summary.window.end-summary.window.start;$("#status").textContent=`${summary.domains.length} domains · ${duration(covered)} data in ${duration(selected)} range`}catch(e){$("#status").textContent=`Could not load report: ${e.message}`}}
async function load(){try{$("#status").textContent="Loading…";const range=$("#range").value;summary=await fetch(manifest.summaries[range]).then(r=>r.json());bars($("#activity"),summary.domains,[{key:"hits",label:"Hits",class:"bar-hit",color:"#6999ff"},{key:"visitors",label:"Visitors",class:"bar-visitor",color:"#4ed7cf"}]);bars($("#bandwidth"),summary.domains,[{key:"bytes",label:"Bandwidth",class:"bar-bytes",color:"#ffb454"}],{format:bytes});const select=$("#domain"),current=select.value;select.textContent="";for(const [value,label] of [["all","All domains"],...manifest.domains.map(x=>[x.id,x.name])]){const o=document.createElement("option");o.value=value;o.textContent=label;select.append(o)}select.value=[...select.options].some(x=>x.value===current)?current:"all";tables();await loadLine();const covered=Math.max(0,Math.min(summary.window.end,summary.window.data_end)-Math.max(summary.window.start,summary.window.data_start));const selected=summary.window.end-summary.window.start;$("#status").textContent=`${summary.domains.length} domains · ${duration(covered)} data in ${duration(selected)} range`}catch(e){$("#status").textContent=`Could not load report: ${e.message}`}}
document.addEventListener("DOMContentLoaded",async()=>{manifest=await fetch("data/manifest.json").then(r=>r.json());$("#range").addEventListener("change",load);$("#domain").addEventListener("change",loadLine);$("#metric").addEventListener("change",tables);load()});